name: Build, Generate Tags & Push To Remote Repo

on:
  push:
    branches:
      - master

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install dependencies
        run: yarn

  publish:
    needs: [ 'checkout' ]
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: yarn

      - name: Build the dependencies
        run: yarn build

      - name: Bump version & push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'Test CI'
          git config --global user.email 'test@users.noreply.github.com'

          npm version patch --force -m "Bump version to %s [skip ci]"
          git push origin && git push --tags

#      - name: Commit changes
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        run: |
#          git config --global user.name 'Test CI'
#          git config --global user.email 'test@users.noreply.github.com'
#          git add .
#          git commit -m "Bump package version [skip ci]"
#          git push

      - name: Push Tag To Remote Repo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git tag -a ${{ steps.bump-version.outputs.version }} -m "Bump version to ${{ steps.bump-version.outputs.version }} [skip ci]"
          git push origin https://github.com/KuyeselaOrganization/test-project-releases.git ${{ github.ref }}
