name: Push Latest Tag to Releases Repo

on:
 workflow_dispatch:


jobs:
  push-latest-tag:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./HapiApi

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch Tags
        run: git fetch --tags

      - name: Get Latest Tag
        id: latest-tag
        run: |
          latestTag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "Latest tag is $latestTag"
          echo "::set-output name=latest_tag::$latestTag"

      - name: Push Latest Tag To Releases Repo
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git push https://github.com/KuyeselaOrganization/test-project-releases.git refs/tags/${{ steps.latest-tag.outputs.latest_tag }}
